{{- if .Values.kubernetes.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.kubernetes.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "github-runner.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
