{{- if .Values.kubernetes.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "github-runner.serviceAccountName" . }}
  namespace: {{ .Values.kubernetes.namespace }}
  labels:
    {{- include "github-runner.labels" . | nindent 4 }}
  {{- with .Values.kubernetes.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
