---
# HAProxy handlers

- name: Restart HAProxy
  ansible.builtin.systemd:
    name: haproxy
    state: restarted
  listen: Restart HAProxy

- name: Reload HAProxy
  ansible.builtin.systemd:
    name: haproxy
    state: reloaded
  listen: Reload HAProxy
